import type { Sale, Expense, Product, StockItem, ChatMessage } from '../types';

// Helper to generate dates relative to today (2026-05-31)
function daysAgo(days: number): string {
  const d = new Date('2026-05-31');
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Miniatura Dragão Medieval',
    sku: 'MIN-DRG-001',
    category: 'Miniaturas',
    productionCost: 8.50,
    packagingCost: 2.00,
    printTime: 6.5,
    weightGrams: 85,
    material: 'PLA+',
    defaultPrice: 49.90,
    currentStock: 12,
    marketplaces: [
      { name: 'Mercado Livre', price: 49.90, active: true },
      { name: 'Shopee', price: 44.90, active: true },
      { name: 'TikTok Shop', price: 47.90, active: true },
    ],
    unitCost: 10.50,
    unitProfit: 34.90,
    margin: 69.9,
    roi: 332.4,
  },
  {
    id: 'p2',
    name: 'Suporte para Fone de Ouvido',
    sku: 'SUP-FNE-001',
    category: 'Suportes',
    productionCost: 5.20,
    packagingCost: 1.50,
    printTime: 3.0,
    weightGrams: 120,
    material: 'PLA',
    defaultPrice: 34.90,
    currentStock: 28,
    marketplaces: [
      { name: 'Mercado Livre', price: 34.90, active: true },
      { name: 'Shopee', price: 29.90, active: true },
      { name: 'Amazon', price: 39.90, active: true },
    ],
    unitCost: 6.70,
    unitProfit: 23.90,
    margin: 68.5,
    roi: 256.7,
  },
  {
    id: 'p3',
    name: 'Organizador de Cabos para Mesa',
    sku: 'ORG-CAB-001',
    category: 'Organizadores',
    productionCost: 3.80,
    packagingCost: 1.20,
    printTime: 2.5,
    weightGrams: 95,
    material: 'PLA',
    defaultPrice: 24.90,
    currentStock: 35,
    marketplaces: [
      { name: 'Mercado Livre', price: 24.90, active: true },
      { name: 'Shopee', price: 19.90, active: true },
      { name: 'TikTok Shop', price: 22.90, active: true },
    ],
    unitCost: 5.00,
    unitProfit: 15.70,
    margin: 63.1,
    roi: 214.0,
  },
  {
    id: 'p4',
    name: 'Vaso Decorativo Geométrico',
    sku: 'VAS-GEO-001',
    category: 'Decoração',
    productionCost: 12.00,
    packagingCost: 3.00,
    printTime: 9.0,
    weightGrams: 210,
    material: 'PLA+',
    defaultPrice: 69.90,
    currentStock: 8,
    marketplaces: [
      { name: 'Mercado Livre', price: 69.90, active: true },
      { name: 'Shopee', price: 64.90, active: true },
    ],
    unitCost: 15.00,
    unitProfit: 49.90,
    margin: 71.4,
    roi: 232.7,
  },
  {
    id: 'p5',
    name: 'Porta Especiarias 6 Potes',
    sku: 'PRT-ESP-001',
    category: 'Cozinha',
    productionCost: 18.50,
    packagingCost: 4.00,
    printTime: 12.0,
    weightGrams: 380,
    material: 'PETG',
    defaultPrice: 89.90,
    currentStock: 5,
    marketplaces: [
      { name: 'Mercado Livre', price: 89.90, active: true },
      { name: 'Amazon', price: 94.90, active: true },
    ],
    unitCost: 22.50,
    unitProfit: 55.40,
    margin: 61.6,
    roi: 146.2,
  },
  {
    id: 'p6',
    name: 'Chaveiro Personalizado (pack 5un)',
    sku: 'CHA-PER-005',
    category: 'Acessórios',
    productionCost: 4.50,
    packagingCost: 1.00,
    printTime: 1.5,
    weightGrams: 30,
    material: 'PLA',
    defaultPrice: 19.90,
    currentStock: 60,
    marketplaces: [
      { name: 'Shopee', price: 19.90, active: true },
      { name: 'TikTok Shop', price: 17.90, active: true },
      { name: 'Venda Direta', price: 22.00, active: true },
    ],
    unitCost: 5.50,
    unitProfit: 12.40,
    margin: 62.3,
    roi: 125.5,
  },
  {
    id: 'p7',
    name: 'Suporte de Celular para Mesa',
    sku: 'SUP-CEL-001',
    category: 'Suportes',
    productionCost: 6.00,
    packagingCost: 1.80,
    printTime: 4.0,
    weightGrams: 150,
    material: 'PETG',
    defaultPrice: 39.90,
    currentStock: 20,
    marketplaces: [
      { name: 'Mercado Livre', price: 39.90, active: true },
      { name: 'Shopee', price: 35.90, active: true },
      { name: 'Amazon', price: 44.90, active: true },
    ],
    unitCost: 7.80,
    unitProfit: 28.30,
    margin: 70.9,
    roi: 262.8,
  },
  {
    id: 'p8',
    name: 'Figura Decorativa Astronauta',
    sku: 'FIG-AST-001',
    category: 'Decoração',
    productionCost: 15.00,
    packagingCost: 3.50,
    printTime: 11.0,
    weightGrams: 280,
    material: 'PLA+ Silk',
    defaultPrice: 79.90,
    currentStock: 6,
    marketplaces: [
      { name: 'Mercado Livre', price: 79.90, active: true },
      { name: 'TikTok Shop', price: 74.90, active: true },
    ],
    unitCost: 18.50,
    unitProfit: 55.40,
    margin: 69.3,
    roi: 199.5,
  },
];

export const mockSales: Sale[] = [
  // May 2026 sales
  {
    id: 's1',
    productId: 'p1',
    productName: 'Miniatura Dragão Medieval',
    quantity: 2,
    unitPrice: 49.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(1),
    marketplaceFee: 12,
    shippingCost: 8.00,
    productionCost: 10.50,
    profit: 55.22,
    status: 'completed',
  },
  {
    id: 's2',
    productId: 'p2',
    productName: 'Suporte para Fone de Ouvido',
    quantity: 3,
    unitPrice: 29.90,
    marketplace: 'Shopee',
    date: daysAgo(1),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 6.70,
    profit: 57.13,
    status: 'completed',
  },
  {
    id: 's3',
    productId: 'p3',
    productName: 'Organizador de Cabos para Mesa',
    quantity: 5,
    unitPrice: 22.90,
    marketplace: 'TikTok Shop',
    date: daysAgo(2),
    marketplaceFee: 10,
    shippingCost: 0,
    productionCost: 5.00,
    profit: 77.95,
    status: 'completed',
  },
  {
    id: 's4',
    productId: 'p7',
    productName: 'Suporte de Celular para Mesa',
    quantity: 2,
    unitPrice: 39.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(3),
    marketplaceFee: 12,
    shippingCost: 6.00,
    productionCost: 7.80,
    profit: 49.84,
    status: 'completed',
  },
  {
    id: 's5',
    productId: 'p4',
    productName: 'Vaso Decorativo Geométrico',
    quantity: 1,
    unitPrice: 64.90,
    marketplace: 'Shopee',
    date: daysAgo(4),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 15.00,
    profit: 40.81,
    status: 'completed',
  },
  {
    id: 's6',
    productId: 'p6',
    productName: 'Chaveiro Personalizado (pack 5un)',
    quantity: 10,
    unitPrice: 17.90,
    marketplace: 'TikTok Shop',
    date: daysAgo(5),
    marketplaceFee: 10,
    shippingCost: 0,
    productionCost: 5.50,
    profit: 105.90,
    status: 'completed',
  },
  {
    id: 's7',
    productId: 'p8',
    productName: 'Figura Decorativa Astronauta',
    quantity: 1,
    unitPrice: 79.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(6),
    marketplaceFee: 12,
    shippingCost: 10.00,
    productionCost: 18.50,
    profit: 41.51,
    status: 'completed',
  },
  {
    id: 's8',
    productId: 'p5',
    productName: 'Porta Especiarias 6 Potes',
    quantity: 1,
    unitPrice: 89.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(7),
    marketplaceFee: 12,
    shippingCost: 12.00,
    productionCost: 22.50,
    profit: 44.61,
    status: 'completed',
  },
  {
    id: 's9',
    productId: 'p1',
    productName: 'Miniatura Dragão Medieval',
    quantity: 1,
    unitPrice: 49.90,
    marketplace: 'Shopee',
    date: daysAgo(8),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 10.50,
    profit: 32.41,
    status: 'completed',
  },
  {
    id: 's10',
    productId: 'p3',
    productName: 'Organizador de Cabos para Mesa',
    quantity: 8,
    unitPrice: 24.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(9),
    marketplaceFee: 12,
    shippingCost: 15.00,
    productionCost: 5.00,
    profit: 121.08,
    status: 'completed',
  },
  {
    id: 's11',
    productId: 'p2',
    productName: 'Suporte para Fone de Ouvido',
    quantity: 4,
    unitPrice: 34.90,
    marketplace: 'Amazon',
    date: daysAgo(10),
    marketplaceFee: 15,
    shippingCost: 0,
    productionCost: 6.70,
    profit: 88.44,
    status: 'completed',
  },
  {
    id: 's12',
    productId: 'p6',
    productName: 'Chaveiro Personalizado (pack 5un)',
    quantity: 20,
    unitPrice: 22.00,
    marketplace: 'Venda Direta',
    date: daysAgo(11),
    marketplaceFee: 0,
    shippingCost: 0,
    productionCost: 5.50,
    profit: 330.00,
    status: 'completed',
  },
  {
    id: 's13',
    productId: 'p7',
    productName: 'Suporte de Celular para Mesa',
    quantity: 3,
    unitPrice: 35.90,
    marketplace: 'Shopee',
    date: daysAgo(12),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 7.80,
    profit: 68.50,
    status: 'completed',
  },
  {
    id: 's14',
    productId: 'p4',
    productName: 'Vaso Decorativo Geométrico',
    quantity: 2,
    unitPrice: 69.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(14),
    marketplaceFee: 12,
    shippingCost: 14.00,
    productionCost: 15.00,
    profit: 79.44,
    status: 'completed',
  },
  {
    id: 's15',
    productId: 'p8',
    productName: 'Figura Decorativa Astronauta',
    quantity: 2,
    unitPrice: 74.90,
    marketplace: 'TikTok Shop',
    date: daysAgo(15),
    marketplaceFee: 10,
    shippingCost: 0,
    productionCost: 18.50,
    profit: 97.12,
    status: 'completed',
  },
  {
    id: 's16',
    productId: 'p5',
    productName: 'Porta Especiarias 6 Potes',
    quantity: 2,
    unitPrice: 94.90,
    marketplace: 'Amazon',
    date: daysAgo(18),
    marketplaceFee: 15,
    shippingCost: 0,
    productionCost: 22.50,
    profit: 116.32,
    status: 'completed',
  },
  {
    id: 's17',
    productId: 'p1',
    productName: 'Miniatura Dragão Medieval',
    quantity: 3,
    unitPrice: 47.90,
    marketplace: 'TikTok Shop',
    date: daysAgo(20),
    marketplaceFee: 10,
    shippingCost: 0,
    productionCost: 10.50,
    profit: 97.47,
    status: 'completed',
  },
  {
    id: 's18',
    productId: 'p3',
    productName: 'Organizador de Cabos para Mesa',
    quantity: 6,
    unitPrice: 19.90,
    marketplace: 'Shopee',
    date: daysAgo(22),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 5.00,
    profit: 72.55,
    status: 'completed',
  },
  // April 2026 (last month) sales for comparison
  {
    id: 's19',
    productId: 'p2',
    productName: 'Suporte para Fone de Ouvido',
    quantity: 5,
    unitPrice: 34.90,
    marketplace: 'Mercado Livre',
    date: daysAgo(35),
    marketplaceFee: 12,
    shippingCost: 10.00,
    productionCost: 6.70,
    profit: 107.75,
    status: 'completed',
  },
  {
    id: 's20',
    productId: 'p6',
    productName: 'Chaveiro Personalizado (pack 5un)',
    quantity: 15,
    unitPrice: 19.90,
    marketplace: 'Shopee',
    date: daysAgo(38),
    marketplaceFee: 14,
    shippingCost: 0,
    productionCost: 5.50,
    profit: 173.55,
    status: 'completed',
  },
  {
    id: 's21',
    productId: 'p7',
    productName: 'Suporte de Celular para Mesa',
    quantity: 4,
    unitPrice: 39.90,
    marketplace: 'Amazon',
    date: daysAgo(42),
    marketplaceFee: 15,
    shippingCost: 0,
    productionCost: 7.80,
    profit: 104.52,
    status: 'completed',
  },
];

export const mockExpenses: Expense[] = [
  // May 2026 expenses
  {
    id: 'e1',
    value: 89.90,
    date: daysAgo(3),
    category: 'Filamento',
    supplier: 'Polymaker BR',
    paymentMethod: 'Pix',
    notes: 'PLA+ Branco 1kg',
  },
  {
    id: 'e2',
    value: 149.00,
    date: daysAgo(5),
    category: 'Filamento',
    supplier: 'Bambu Lab Store',
    paymentMethod: 'Cartão Crédito',
    notes: 'PLA Silk Rainbow 2 rolos',
  },
  {
    id: 'e3',
    value: 67.50,
    date: daysAgo(7),
    category: 'Embalagens',
    supplier: 'Embalagens Express',
    paymentMethod: 'Boleto',
    notes: 'Caixinhas de papelão 50un + papel crepom',
  },
  {
    id: 'e4',
    value: 42.80,
    date: daysAgo(9),
    category: 'Energia',
    supplier: 'CEMIG',
    paymentMethod: 'Débito Automático',
    notes: 'Conta de luz - parte proporcional da impressora',
  },
  {
    id: 'e5',
    value: 38.90,
    date: daysAgo(11),
    category: 'Embalagens',
    supplier: 'Mercado Livre Lojas',
    paymentMethod: 'Pix',
    notes: 'Plástico bolha 50m + fita adesiva',
  },
  {
    id: 'e6',
    value: 199.00,
    date: daysAgo(13),
    category: 'Filamento',
    supplier: 'Creality Store BR',
    paymentMethod: 'Cartão Crédito',
    notes: 'PETG Transparente 2kg + PLA Matte 1kg',
  },
  {
    id: 'e7',
    value: 29.90,
    date: daysAgo(15),
    category: 'Software e Assinaturas',
    supplier: 'Canva Pro',
    paymentMethod: 'Cartão Crédito',
    notes: 'Assinatura mensal Canva para fotos produtos',
  },
  {
    id: 'e8',
    value: 55.00,
    date: daysAgo(17),
    category: 'Marketing',
    supplier: 'Meta Ads',
    paymentMethod: 'Cartão Crédito',
    notes: 'Impulsionamento Instagram - produtos novos',
  },
  {
    id: 'e9',
    value: 12.50,
    date: daysAgo(19),
    category: 'Frete e Logística',
    supplier: 'Correios',
    paymentMethod: 'Dinheiro',
    notes: 'Envio de amostra para cliente atacado',
  },
  {
    id: 'e10',
    value: 85.00,
    date: daysAgo(21),
    category: 'Manutenção',
    supplier: 'Print3D Peças',
    paymentMethod: 'Pix',
    notes: 'Nozzle 0.4mm + extrusor Bowden',
  },
  {
    id: 'e11',
    value: 110.00,
    date: daysAgo(23),
    category: 'Filamento',
    supplier: 'AmazonBR',
    paymentMethod: 'Pix',
    notes: 'PLA+ Vermelho e Azul 1kg cada',
  },
  {
    id: 'e12',
    value: 22.00,
    date: daysAgo(25),
    category: 'Embalagens',
    supplier: 'Loja do Embalador',
    paymentMethod: 'Dinheiro',
    notes: 'Envelopes plásticos transparentes 100un',
  },
  // April 2026 expenses
  {
    id: 'e13',
    value: 95.00,
    date: daysAgo(35),
    category: 'Filamento',
    supplier: 'Polymaker BR',
    paymentMethod: 'Pix',
    notes: 'PLA+ Preto 1kg',
  },
  {
    id: 'e14',
    value: 48.00,
    date: daysAgo(38),
    category: 'Energia',
    supplier: 'CEMIG',
    paymentMethod: 'Débito Automático',
    notes: 'Conta de luz abril',
  },
  {
    id: 'e15',
    value: 75.00,
    date: daysAgo(40),
    category: 'Marketing',
    supplier: 'Google Ads',
    paymentMethod: 'Cartão Crédito',
    notes: 'Campanhas Google Shopping',
  },
  {
    id: 'e16',
    value: 60.00,
    date: daysAgo(42),
    category: 'Embalagens',
    supplier: 'Embalagens Express',
    paymentMethod: 'Boleto',
    notes: 'Caixas personalizadas com logo',
  },
  {
    id: 'e17',
    value: 35.00,
    date: daysAgo(45),
    category: 'Ferramentas',
    supplier: 'Shopee',
    paymentMethod: 'Pix',
    notes: 'Espátulas + raspador de cama',
  },
  {
    id: 'e18',
    value: 180.00,
    date: daysAgo(48),
    category: 'Filamento',
    supplier: 'Bambu Lab Store',
    paymentMethod: 'Cartão Crédito',
    notes: 'PETG Preto + Branco 2kg cada',
  },
  {
    id: 'e19',
    value: 25.00,
    date: daysAgo(50),
    category: 'Software e Assinaturas',
    supplier: 'Bambu Handy',
    paymentMethod: 'Cartão Crédito',
    notes: 'Assinatura cloud slicing',
  },
  {
    id: 'e20',
    value: 18.90,
    date: daysAgo(55),
    category: 'Frete e Logística',
    supplier: 'Melhor Envio',
    paymentMethod: 'Pix',
    notes: 'Etiquetas pré-pagas 10un',
  },
];

export const mockStockItems: StockItem[] = [
  {
    id: 'st1',
    name: 'PLA+ Branco 1kg',
    quantity: 2.5,
    unit: 'kg',
    totalCost: 224.75,
    unitCost: 89.90,
    supplier: 'Polymaker BR',
    purchaseDate: daysAgo(3),
    minStock: 1,
    category: 'Filamentos',
  },
  {
    id: 'st2',
    name: 'PLA+ Preto 1kg',
    quantity: 1.2,
    unit: 'kg',
    totalCost: 107.88,
    unitCost: 89.90,
    supplier: 'Polymaker BR',
    purchaseDate: daysAgo(35),
    minStock: 1,
    category: 'Filamentos',
  },
  {
    id: 'st3',
    name: 'PETG Transparente 1kg',
    quantity: 1.8,
    unit: 'kg',
    totalCost: 179.82,
    unitCost: 99.90,
    supplier: 'Creality Store BR',
    purchaseDate: daysAgo(13),
    minStock: 0.5,
    category: 'Filamentos',
  },
  {
    id: 'st4',
    name: 'PLA Silk Rainbow 1kg',
    quantity: 0.4,
    unit: 'kg',
    totalCost: 59.60,
    unitCost: 149.00,
    supplier: 'Bambu Lab Store',
    purchaseDate: daysAgo(5),
    minStock: 0.5,
    category: 'Filamentos',
  },
  {
    id: 'st5',
    name: 'PLA+ Vermelho 1kg',
    quantity: 0.8,
    unit: 'kg',
    totalCost: 88.00,
    unitCost: 110.00,
    supplier: 'AmazonBR',
    purchaseDate: daysAgo(25),
    minStock: 0.5,
    category: 'Filamentos',
  },
  {
    id: 'st6',
    name: 'PLA+ Silk Dourado 1kg',
    quantity: 0.2,
    unit: 'kg',
    totalCost: 29.80,
    unitCost: 149.00,
    supplier: 'Bambu Lab Store',
    purchaseDate: daysAgo(20),
    minStock: 0.5,
    category: 'Filamentos',
  },
  {
    id: 'st7',
    name: 'Caixas Papelão P (10x10x5)',
    quantity: 45,
    unit: 'un',
    totalCost: 33.75,
    unitCost: 0.75,
    supplier: 'Embalagens Express',
    purchaseDate: daysAgo(3),
    minStock: 20,
    category: 'Embalagens',
  },
  {
    id: 'st8',
    name: 'Caixas Papelão M (20x15x10)',
    quantity: 18,
    unit: 'un',
    totalCost: 27.00,
    unitCost: 1.50,
    supplier: 'Embalagens Express',
    purchaseDate: daysAgo(7),
    minStock: 20,
    category: 'Embalagens',
  },
  {
    id: 'st9',
    name: 'Plástico Bolha 50m',
    quantity: 1,
    unit: 'rolo',
    totalCost: 25.90,
    unitCost: 25.90,
    supplier: 'Mercado Livre Lojas',
    purchaseDate: daysAgo(11),
    minStock: 1,
    category: 'Embalagens',
  },
  {
    id: 'st10',
    name: 'Envelopes Plásticos Transparentes',
    quantity: 80,
    unit: 'un',
    totalCost: 17.60,
    unitCost: 0.22,
    supplier: 'Loja do Embalador',
    purchaseDate: daysAgo(25),
    minStock: 30,
    category: 'Embalagens',
  },
  {
    id: 'st11',
    name: 'Nozzle 0.4mm (pack 5)',
    quantity: 3,
    unit: 'un',
    totalCost: 51.00,
    unitCost: 17.00,
    supplier: 'Print3D Peças',
    purchaseDate: daysAgo(21),
    minStock: 2,
    category: 'Peças',
  },
  {
    id: 'st12',
    name: 'Papel Crepom Colorido',
    quantity: 5,
    unit: 'rolo',
    totalCost: 12.50,
    unitCost: 2.50,
    supplier: 'Embalagens Express',
    purchaseDate: daysAgo(7),
    minStock: 3,
    category: 'Embalagens',
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg1',
    role: 'assistant',
    content: 'Olá, Vinny! Sou seu assistente financeiro especializado em negócios de impressão 3D. Posso analisar seus dados de vendas, gastos e produtos para te ajudar a tomar decisões mais inteligentes. Como posso te ajudar hoje?',
    timestamp: new Date('2026-05-31T09:00:00').toISOString(),
  },
  {
    id: 'msg2',
    role: 'user',
    content: 'Qual produto deu mais lucro esse mês?',
    timestamp: new Date('2026-05-31T09:01:00').toISOString(),
  },
  {
    id: 'msg3',
    role: 'assistant',
    content: 'Com base nos dados de maio de 2026, o produto mais lucrativo foi o **Chaveiro Personalizado (pack 5un)**, com R$ 435,90 em lucro total (30 unidades vendidas). A margem é de 62,3% e o ROI de 125,5%.\n\nEm segundo lugar vem o **Organizador de Cabos para Mesa** com R$ 271,58 em lucro (19 unidades vendidas).\n\nVale destacar que os chaveiros têm o menor preço mas compensam no volume. Já os produtos de decoração como o Vaso Geométrico têm margens maiores por unidade (71%). Minha sugestão é aumentar a produção de chaveiros para atacado e focar em lançar novas peças decorativas premium!',
    timestamp: new Date('2026-05-31T09:01:30').toISOString(),
  },
];
